### ISSUE TITLE
クリックしても自動入力されない

### ISSUE THREAD

**Issue by kyasby** [kcm0ri/nu-cas-6-digit-autofiller#1]
認証画面でクリックしても自動入力されない気がします。
私の環境だけでしたら，申し訳ありません。

**Comment by kentcmori** [comment]
複数の環境で動作することを確認済みですので、もう一度コード等確認頂けますでしょうか。

your seed部分のコピー&ペーストを間違えていると自動入力されない場合があります。
また、Chrome://extensionsでエラーが出ていないかもご確認ください。
